In [93]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [94]:
veri = pd.read_csv("Advertising.csv")
veriDf = pd.DataFrame(veri)
veriDf = veriDf.iloc[:,1:]
veriDf.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [95]:
X = veriDf.drop(["sales"],axis=1)
y = veriDf[["sales"]]

# statsmodel ile model kurmak

In [96]:
import statsmodels.api as sm
linearModel = sm.OLS(y,X)
model = linearModel.fit()

In [97]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sat, 25 Jan 2025   Prob (F-statistic):                   2.43e-171
Time:                        23:21:18   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# scikit learn ile model kurma

In [98]:
from sklearn.linear_model import LinearRegression

In [99]:
reg = LinearRegression()
model = reg.fit(X,y)

In [100]:
model.intercept_

array([2.93888937])

In [101]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

# tahmin

In [102]:
sonuc = 2.94 + 30*0.04 + 0.19*10 - 0.001*40
sonuc

5.999999999999999

In [103]:
yeni_veri = [[30,20],[10,30],[40,50]]
yeniveriDf = pd.DataFrame(yeni_veri).T
yeniveriDf

0   1   2
0  30  10  40
1  20  30  50

In [104]:
model.predict(yeniveriDf)

C:\Users\omerd\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918],
       [9.45820813]])

In [105]:
from sklearn.metrics import mean_squared_error

In [106]:
tahmin = model.predict(X[0:10])
tahmin2 = model.predict(X)
denemeY = y.iloc[0:10]
denemeY = np.array(denemeY)

In [113]:
MSE = mean_squared_error(y,tahmin2)
MSE

2.784126314510936

In [117]:
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697